apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hungryman-search-proc
  labels:
    app.kubernetes.io/part-of: hungryman
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hungryman-search-proc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.7.0
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-web
          spring-boot-convention/service-intent-rabbitmq
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        services.conventions.apps.tanzu.vmware.com/rabbitmq: amqp-client/5.14.2
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hungryman
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hungryman-search-proc
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080"
        image: reg.perfect300rock.com/tapdev/supply-chain/hungryman-search-proc-workloads@sha256:754a4f94bde41d79a3ca514e17a02d59333d2a093655a4b6b3e007a0d411c12c
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

