apiVersion: apps/v1
kind: Deployment
metadata:
  name: hungryman-availability
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: hungryman-availability
    apps.tanzu.vmware.com/workload-type: server
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: hungryman-availability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: hungryman-availability
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: hungryman-availability
      conventions.apps.tanzu.vmware.com/framework: spring-boot
      networking.knative.dev/visibility: cluster-local
      services.conventions.apps.tanzu.vmware.com/postgres: workload
      services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
      tanzu.app.live.view: "true"
      tanzu.app.live.view.application.actuator.port: "8081"
      tanzu.app.live.view.application.flavours: spring-boot
      tanzu.app.live.view.application.name: hungryman-availability
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.7.4
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/service-intent-postgres
          spring-boot-convention/service-intent-rabbitmq
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"hungryman-availability","apps.tanzu.vmware.com/workload-type":"server","networking.knative.dev/visibility":"cluster-local"},"name":"hungryman-availability","namespace":"workloads"},"spec":{"params":[{"name":"ports","value":[{"containerPort":8080,"name":"http","port":80}]}],"serviceClaims":[{"name":"rmq","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"rmq-hungryman"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/gm2552/hungryman.git"},"subPath":"hungryman-availability"}}}
        services.conventions.apps.tanzu.vmware.com/postgres: r2dbc-postgresql/0.9.2.RELEASE
        services.conventions.apps.tanzu.vmware.com/rabbitmq: amqp-client/5.14.2
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hungryman-availability
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: hungryman-availability
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        networking.knative.dev/visibility: cluster-local
        services.conventions.apps.tanzu.vmware.com/postgres: workload
        services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: hungryman-availability
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080"
        image: reg.perfect300rock.com/tapdev/supply-chain/hungryman-availability-workloads@sha256:a8a6d9d54fa0fb5a85ef4a0a59481a93a320e760597c7db686e6cde62b2805f1
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: hungryman-availability
  labels:
    app.kubernetes.io/part-of: hungryman-availability
    apps.tanzu.vmware.com/workload-type: server
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: hungryman-availability
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: hungryman-availability
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: hungryman-availability
    conventions.apps.tanzu.vmware.com/framework: spring-boot
    networking.knative.dev/visibility: cluster-local
    services.conventions.apps.tanzu.vmware.com/postgres: workload
    services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8081"
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.name: hungryman-availability
  ports:
  - targetPort: 8080
    port: 8080
    name: "8080"
  - targetPort: 8080
    port: 80
    name: http

