apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-order
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/workload-type: server
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: acme-order
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: acme-fitness-store
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: acme-order
      networking.knative.dev/visibility: cluster-local
      tanzu.app.live.view: "true"
      tanzu.app.live.view.application.flavours: steeltoe
      tanzu.app.live.view.application.name: acme-order
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"acme-fitness-store","apps.tanzu.vmware.com/workload-type":"server","networking.knative.dev/visibility":"cluster-local"},"name":"acme-order","namespace":"workloads"},"spec":{"env":[{"name":"AcmeServiceSettings__AuthUrl","value":"http://authserver.tsmdemo.perfect300rock.com"},{"name":"PAYMENT_SERVICE_SERVICE_HOST","value":"acme-payment"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"ports","value":[{"containerPort":8080,"name":"http","port":80}]}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/gm2552/acme-fitness-store"},"subPath":"apps/acme-order"}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: acme-fitness-store
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: acme-order
        networking.knative.dev/visibility: cluster-local
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: acme-order
    spec:
      containers:
      - env:
        - name: AcmeServiceSettings__AuthUrl
          value: http://authserver.tsmdemo.perfect300rock.com
        - name: PAYMENT_SERVICE_SERVICE_HOST
          value: acme-payment
        image: reg.perfect300rock.com/tapdev/supply-chain/acme-order-workloads@sha256:750206b372d88ea34288b2df74d35fd6908a0feda2b90b02aa38593813eb3dc4
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: acme-order
  labels:
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/workload-type: server
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: acme-order
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: acme-order
    networking.knative.dev/visibility: cluster-local
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: acme-order
  ports:
  - targetPort: 8080
    port: 80
    name: http

