apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  creationTimestamp: "2022-09-15T18:28:08Z"
  generation: 1
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: hungryman-api-gateway
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/workload-type: server
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: hungryman
    carto.run/workload-namespace: my-apps
  name: hungryman
  namespace: hungryman
spec:
  params:
  - name: gitops_ssh_secret
    value: tap-play-gitops-secret
  - name: gitops_sub_path
    value: config/workloads/hungryman
  source:
    git:
      ref:
        branch: main
      url: https://github.com/gm2552/tap-play-gitops.git
 
