apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-shopping
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: acme-shopping
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: acme-fitness-store
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: acme-shopping
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"acme-fitness-store","apps.tanzu.vmware.com/workload-type":"server"},"name":"acme-shopping","namespace":"workloads"},"spec":{"build":{"env":[{"name":"BP_NODE_RUN_SCRIPTS","value":"build"},{"name":"BP_WEB_SERVER","value":"httpd"},{"name":"BP_WEB_SERVER_ROOT","value":"public"},{"name":"BP_WEB_SERVER_ENABLE_PUSH_STATE","value":"true"},{"name":"PORT","value":"8080"}]},"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"ports","value":[{"containerPort":8080,"name":"http","port":80}]}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/gm2552/acme-fitness-store"},"subPath":"apps/acme-shopping"}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: acme-fitness-store
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: acme-shopping
    spec:
      containers:
      - image: reg.perfect300rock.com/tapdev/supply-chain/acme-shopping-workloads@sha256:4ff6186ee4a11500d48f492b964d043ef421f0accb1eef73bfa4494bf838bfee
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: acme-shopping
  labels:
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: acme-shopping
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: acme-shopping
  ports:
  - targetPort: 8080
    port: 80
    name: http

